// Semua potongan teks Indonesia untuk label silsilah ada di sini, supaya
// langkah 1.14 cukup memindahkannya ke src/teks/id.js.
export const KATA = {
  almL: 'Alm.',
  almP: 'Almh.',
  almNetral: 'Alm./Almh.',
  pasanganDari: 'Pasangan dari',
  bercerai: 'bercerai',
  dari: 'dari',
  dan: 'dan',
  diriSendiri: 'Diri sendiri',
  lahirDi: 'di',
  sekitar: 'sekitar',
  anakKe: 'Anak ke-',
  jenisPasangan: { istri: 'istri', suami: 'suami', pasangan: 'pasangan' },
  jenisAnak: { kandung: null, sambung: 'Anak sambung', angkat: 'Anak angkat' },
  generasiKe: 'Generasi ke-',
  statusPernikahan: {
    menikah: 'Menikah',
    cerai: 'Bercerai',
    tidak_diketahui: 'Status tidak diketahui',
  },
  bulan: [
    'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni',
    'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember',
  ],
  kerabat: {
    bapak: 'Bapak',
    ibu: 'Ibu',
    orangTua: 'Orang tua',
    mbah: 'Mbah',
    mbahBuyut: 'Mbah buyut',
    mbahCanggah: 'Mbah canggah',
    mbahWareng: 'Mbah wareng',
    kakak: 'Kakak',
    adik: 'Adik',
    kakakAdik: 'Kakak/Adik',
    ipar: 'Ipar',
    keponakan: 'Keponakan',
    sepupu: 'Sepupu',
    anak: 'Anak',
    cucu: 'Cucu',
    cicit: 'Cicit',
    suami: 'Suami',
    istri: 'Istri',
    pasangan: 'Pasangan',
    pakdhe: 'Pakdhe',
    budhe: 'Budhe',
    paklik: 'Paklik',
    bulik: 'Bulik',
    pakdheBudhe: 'Pakdhe/Budhe',
    paklikBulik: 'Paklik/Bulik',
    pakdhePaklik: 'Pakdhe/Paklik',
    budheBulik: 'Budhe/Bulik',
    pamanBibi: 'Paman/Bibi',
  },
}
