// Semua teks yang dilihat anggota ada di file ini, dalam bahasa Indonesia
// (PLAN.md prinsip 8). Kode lain tidak boleh menulis kalimat sendiri; ia
// mengambil dari sini. Tes memeriksa bahwa tidak ada kata bahasa Inggris
// di dalamnya, dan bahwa setiap kode galat dari file SQL punya pesan.

// Pengecualian: spanduk "MODE CONTOH" sengaja tidak di sini, tetapi di App.jsx dalam
// cabang khusus pengembangan, supaya teksnya tidak ikut ke build produksi.
// Mengisi {nama} dll. di dalam teks: isiTeks('Halo, {nama}!', { nama: 'Bu Contoh' }).
export const isiTeks = (kalimat, nilai = {}) =>
  kalimat.replace(/\{(\w+)\}/g, (_, k) => (nilai[k] ?? `{${k}}`))

export const teks = {
  aplikasi: {
    nama: 'Silsilah Keluarga',
    subjudul: 'Arsip Warisan & Sejarah',
    sedangDibangun: 'Aplikasi ini sedang dibangun.',
    tidakDitemukanJudul: 'Halaman tidak ditemukan',
    tidakDitemukanIsi: 'Alamat yang Anda buka tidak ada di aplikasi ini.',
    kembaliKeAwal: 'Kembali ke halaman awal',
  },

  umum: {
    cobaLagi: 'Coba lagi',
    muatUlang: 'Muat ulang',
    tutup: 'Tutup',
    kembali: 'Kembali',
    memuat: 'Memuat…',
  },

  // Layar keadaan khusus (PLAN.md bagian 14, layar 28). Semuanya tanpa
  // menulis data apa pun.
  layar: {
    memuat: { judul: 'Memuat data', isi: 'Mohon tunggu sebentar.' },
    galat: { judul: 'Terjadi masalah', isi: 'Data belum bisa dimuat.' },
    dipulihkan: {
      judul: 'Aplikasi sedang dipulihkan',
      isi: 'Aplikasi sedang dipulihkan. Silakan coba lagi beberapa saat lagi.',
    },
    belumDisiapkan: {
      judul: 'Aplikasi belum siap',
      isi: 'Aplikasi ini belum tersambung ke database. Hubungi admin keluarga.',
    },
    kosong: {
      judul: 'Belum ada data',
      isi: 'Belum ada data, hubungi admin.',
    },
    belumDiperbarui: {
      judul: 'Database belum diperbarui',
      isi: 'Aplikasi ini membutuhkan pembaruan database yang belum dilakukan. Hubungi admin.',
    },
    offline: {
      judul: 'Tidak ada koneksi internet',
      isi: 'Periksa sambungan internet Anda, lalu coba lagi.',
    },
    sesiHabis: {
      judul: 'Sesi berakhir',
      isi: 'Sesi Anda berakhir. Silakan masuk lagi.',
    },
  },

  // Pesan untuk setiap jenis galat (lihat src/lib/galat.js).
  galat: {
    dipulihkan: 'Aplikasi sedang dipulihkan. Silakan coba lagi beberapa saat lagi.',
    belumDiperbarui: 'Aplikasi membutuhkan pembaruan database yang belum dilakukan. Hubungi admin.',
    offline: 'Tidak ada koneksi internet. Periksa sambungan Anda, lalu coba lagi.',
    jaringan: 'Tidak bisa terhubung ke server. Periksa internet Anda, lalu coba lagi.',
    sesiHabis: 'Sesi Anda berakhir. Silakan masuk lagi.',
    tanpaIzin: 'Anda tidak punya izin untuk melakukan ini.',
    bentrok: 'Data ini baru saja diubah orang lain atau sudah tidak ada. Muat ulang, lalu coba lagi.',
    sibuk: 'Server sedang sibuk. Silakan coba lagi beberapa saat lagi.',
    terlaluSering: 'Terlalu banyak permintaan dalam waktu singkat. Silakan tunggu sebentar, lalu coba lagi.',
    server: 'Server sedang bermasalah. Silakan coba lagi beberapa saat lagi.',
    tidakDikenal:
      'Terjadi masalah yang tidak dikenal. Silakan coba lagi. Kalau terus terjadi, hubungi admin.',
    dataDitolak: 'Data ini tidak bisa disimpan karena tidak memenuhi aturan.',
    tidakDitemukan: 'Data yang dituju tidak ditemukan.',
    // Standar Postgres, tanpa nama batasan yang dikenal.
    standar: {
      '23502': 'Ada isian wajib yang masih kosong.',
      '23503': 'Data ini masih terkait dengan data lain, atau data yang dituju tidak ada lagi.',
      '23505': 'Data ini sudah ada.',
      '23514': 'Data ini tidak memenuhi aturan isian.',
      '22001': 'Ada isian yang terlalu panjang.',
      '22003': 'Ada angka yang terlalu besar atau terlalu kecil.',
      '22007': 'Ada tanggal yang tidak valid.',
      '22008': 'Ada tanggal yang tidak valid.',
      '22P02': 'Ada isian dengan bentuk yang tidak dikenali.',
    },
    // Nama batasan di file SQL 002 dan 004 → pesan untuk anggota.
    batasan: {
      people_birth_valid:
        'Tanggal lahir tidak valid. Bulan membutuhkan tahun, hari membutuhkan bulan, dan tanggalnya harus benar-benar ada.',
      people_death_valid:
        'Tanggal wafat tidak valid. Bulan membutuhkan tahun, hari membutuhkan bulan, dan tanggalnya harus benar-benar ada.',
      people_death_needs_deceased: 'Tanggal atau tempat wafat hanya bisa diisi untuk orang yang sudah wafat.',
      people_death_after_birth: 'Tahun wafat tidak bisa sebelum tahun lahir.',
      people_trash_consistent: 'Status tempat sampah data ini tidak sesuai. Muat ulang, lalu coba lagi.',
      unions_distinct_partners: 'Kedua pasangan tidak bisa orang yang sama.',
      unions_marriage_valid:
        'Tanggal menikah tidak valid. Bulan membutuhkan tahun, hari membutuhkan bulan, dan tanggalnya harus benar-benar ada.',
      unions_end_valid:
        'Tanggal berakhirnya pernikahan tidak valid. Bulan membutuhkan tahun, hari membutuhkan bulan, dan tanggalnya harus benar-benar ada.',
      unions_end_after_marriage: 'Pernikahan tidak bisa berakhir sebelum tahun menikah.',
      unions_trash_consistent: 'Status tempat sampah data ini tidak sesuai. Muat ulang, lalu coba lagi.',
      children_biological_matches_kind:
        'Jenis anak tidak cocok dengan orang tua kandungnya. Anak kandung dari keduanya, anak sambung dari salah satu, anak angkat tanpa hubungan darah.',
      children_trash_consistent: 'Status tempat sampah data ini tidak sesuai. Muat ulang, lalu coba lagi.',
      children_union_child_active: 'Anak ini sudah tercatat di pernikahan ini.',
      children_one_biological_active:
        'Anak ini sudah punya orang tua kandung yang tercatat. Anak sambung atau anak angkat bisa ditambahkan di pernikahan lain.',
      birth_ranks_not_self: 'Seseorang tidak bisa menjadi anak dari dirinya sendiri.',
      birth_ranks_unique_rank: 'Dua anak tidak bisa punya urutan lahir yang sama.',
      members_one_owner: 'Hanya boleh ada satu admin utama.',
      members_permissions_known: 'Izin yang dipilih tidak dikenal.',
      members_permissions_only_assistant: 'Izin tambahan hanya untuk asisten.',
      members_owner_is_member: 'Admin utama tidak bisa diubah.',
      members_revoked_consistent: 'Status anggota dan tanggal pencabutan tidak sesuai.',
      devices_temporary_has_expiry: 'Akses sementara harus punya batas waktu.',
      device_codes_minutes_match_kind: 'Durasi hanya berlaku untuk kode akses sementara.',
    },
    // Verifikasi dua langkah (Supabase Auth). "authenticator" = aplikasi
    // penghasil kode 6 angka, misalnya aplikasi Kata Sandi di iPhone.
    duaLangkah: {
      mfa_verification_failed: 'Kode salah. Masukkan kode 6 angka yang sedang tampil di aplikasi authenticator. Kalau terus salah, pastikan jam di HP sudah benar.',
      mfa_verification_rejected: 'Kode ditolak. Masukkan kode 6 angka yang sedang tampil di aplikasi authenticator.',
      mfa_challenge_expired: 'Waktu memasukkan kode sudah habis. Coba lagi dengan kode yang sedang tampil.',
      insufficient_aal: 'Masukkan dulu kode verifikasi dua langkah di perangkat ini, lalu coba lagi.',
      mfa_factor_name_conflict: 'Authenticator dengan nama ini sudah ada. Muat ulang halaman, lalu coba lagi.',
      mfa_factor_not_found: 'Authenticator ini tidak ditemukan lagi. Muat ulang halaman, lalu coba lagi.',
      too_many_enrolled_mfa_factors: 'Sudah terlalu banyak authenticator terdaftar. Hapus yang tidak dipakai lagi.',
      mfa_totp_enroll_not_enabled: 'Verifikasi dua langkah (TOTP) belum diaktifkan di pengaturan Supabase: Authentication, lalu Multi-Factor.',
      mfa_totp_verify_not_enabled: 'Verifikasi dua langkah (TOTP) belum diaktifkan di pengaturan Supabase: Authentication, lalu Multi-Factor.',
      mfa_ip_address_mismatch: 'Sambungan internet berganti di tengah pendaftaran. Mulai lagi dari awal.',
    },
    // Kode galat buatan kita di file SQL (private.fail). Pesan dari server
    // dipakai kalau berbahasa Indonesia (ada yang memuat nama dan waktu);
    // kalau tidak, pesan di bawah ini.
    kode: {
      AK001: 'Admin utama tidak bisa diubah atau dicabut lewat aplikasi.',
      AK002: 'Hanya admin utama yang boleh melakukan ini.',
      AK003: 'Undangan hanya untuk keturunan dan menantu di silsilah utama.',
      AK004: 'Orang ini belum dewasa (di bawah 18 tahun dan belum menikah), jadi belum bisa diundang.',
      AK005: 'Tanggal lahir orang ini tidak diketahui. Pastikan dulu bahwa ia sudah dewasa.',
      AK006: 'Link undangan ini sudah dipakai, kedaluwarsa, atau dicabut.',
      AK007: 'Perangkat hanya bisa didaftarkan untuk anggota yang aktif, dan perangkat yang sudah dicabut tidak bisa diaktifkan lagi.',
      AK008: 'Kode ini sudah dipakai, kedaluwarsa, atau dicabut.',
      AK009: 'Durasi akses sementara melebihi batas yang diatur admin.',
      AK010: 'Orang ini tercatat sudah wafat.',
      AK011: 'Akun login seorang anggota tidak bisa diganti.',
      AK012: 'Akses anggota ini sudah dicabut. Admin utama perlu mengaktifkannya dulu.',
      AK013: 'Fitur tambah perangkat sedang dimatikan oleh admin.',
      AK014: 'Perangkat dengan akses sementara tidak bisa menambah perangkat lain.',
      AK015: 'Anda tidak punya izin membuat link undangan.',
      AK016: 'Anda tidak punya izin memberi akses sementara.',
      AK017: 'Link dan kode untuk admin utama atau asisten hanya bisa dibuat oleh admin utama.',
      AK018: 'Peran untuk undangan hanya "hanya melihat" atau "anggota". Peran anggota yang sudah terdaftar diubah di daftar anggota.',
      AK019: 'Pendaftaran perangkat ini tidak berlaku lagi. Mintalah link atau kode baru.',
      AK020: 'Sesi ini sudah terdaftar sebagai perangkat lain. Keluar dulu, lalu masuk lagi.',
      AK021: 'Anda belum masuk. Silakan masuk dulu.',
      AK022: 'Durasi akses sementara minimal 30 menit.',
      AK023: 'Akun Anda sedang ditahan sementara, jadi belum bisa menambah perangkat. Hubungi admin.',
      AK024: 'Perangkat ini tidak ditemukan, atau bukan milik Anda.',
      AK025: 'Anda belum masuk dari perangkat ini.',
      AK026: 'Akses sementara ini sudah berakhir atau tidak ditemukan.',
      AK027: 'Ketik PULIHKAN (huruf besar) untuk menjalankan pemulihan darurat.',
      AK028: 'Prosedur darurat hanya bisa dijalankan dari SQL Editor.',
      AK029: 'Admin utama belum ada atau belum pernah masuk.',
      RP001: 'Anda tidak bisa mengirim laporan (hanya melihat, atau sedang ditahan).',
      RP002: 'Data yang dilaporkan tidak ditemukan.',
      RP003: 'Anda sudah mengirim banyak laporan dalam satu jam terakhir. Silakan coba lagi nanti.',
      RP004: 'Anda tidak punya izin untuk menindaklanjuti laporan ini.',
      SL001: 'Hubungan ini membuat silsilah berputar: seseorang tidak bisa menjadi anak dari dirinya sendiri atau dari keturunannya.',
      SL002: 'Pasangan pangkal tidak boleh punya orang tua di silsilah utama.',
      SL003: 'Data yang saling terkait harus berada di pohon yang sama.',
      SL004: 'Pasangan tidak bisa diberi orang tua di silsilah utama. Keluarga asal pasangan dicatat di pohon keluarga asal.',
      SL005: 'Pernikahan dan anak di silsilah utama hanya bisa dicatat di bawah keturunan pasangan pangkal.',
      SL006: 'Bagian data ini tidak boleh diubah setelah dibuat. Buat data baru kalau perlu.',
      SL007: 'Urutan lahir hanya bisa dicatat untuk anak dari orang tua tersebut.',
      SL008: 'Data ini sedang berada di tempat sampah. Pulihkan dulu sebelum dipakai.',
      SL009: 'Pohon keluarga asal hanya bisa dibuat untuk pasangan (bukan keturunan) di silsilah utama.',
      TR001: 'Anda tidak punya izin tempat sampah.',
      TR002: 'Masih ada anak yang aktif. Pindahkan atau buang anak-anaknya dulu.',
      TR003: 'Orang ini punya pohon keluarga asal. Admin utama perlu mengurus pohon itu dulu.',
      TR004: 'Pasangan pangkal dan pernikahannya tidak bisa dibuang atau dihapus.',
      TR005: 'Orang ini anggota aplikasi. Admin utama perlu mencabut aksesnya dulu.',
      TR006: 'Data tidak ditemukan atau sudah di tempat sampah.',
      TR007: 'Data di kelompok ini masih dipakai data lain. Hapus permanen kelompok yang terkait lebih dulu, atau sekaligus.',
      TR008: 'Hanya admin utama (dengan verifikasi dua langkah) yang bisa menghapus permanen.',
      TR009: 'Ketik HAPUS (huruf besar) untuk memastikan penghapusan permanen.',
      TR010: 'Hubungan ini satu-satunya yang menyambungkan orang ini ke silsilah, dan ia sudah berkeluarga. Gunakan "pindahkan ke orang tua lain".',
      TR011: 'Kelompok data ini tidak ada di tempat sampah.',
      TR012: 'Data pohon keluarga asal hanya bisa diatur admin utama.',
      UN001: 'Perubahan ini tidak ditemukan.',
      UN002: 'Perubahan ini sudah dibatalkan.',
      UN003: 'Data ini sudah berubah sejak perubahan itu, jadi tidak bisa dibatalkan otomatis. Silakan ubah secara manual.',
      UN004: 'Hapus permanen tidak bisa dibatalkan. Data hanya bisa dipulihkan dari cadangan oleh admin utama.',
      UN005: 'Pembuatan pohon keluarga asal tidak bisa dibatalkan dari riwayat.',
      UN006: 'Anda hanya bisa membatalkan perubahan Anda sendiri.',
      UN007: 'Hanya admin utama yang bisa membatalkan perubahan ini.',
      UN008: 'Anda tidak bisa membatalkan perubahan (hanya melihat, atau sedang ditahan).',
    },
  },

  navigasi: {
    menu: 'Menu utama',
    beranda: 'Beranda',
    saya: 'Saya',
    kotakMasuk: 'Kotak masuk',
    daftar: 'Daftar',
    bagan: 'Bagan',
    lewatiKeIsi: 'Langsung ke isi halaman',
    privasi: 'Privasi',
  },

  // Layar Masuk (PLAN.md bagian 14, layar 1). Tanpa data apa pun.
  halamanMasuk: {
    judul: 'Silsilah Keluarga',
    sapaan: 'Selamat datang. Aplikasi ini khusus untuk anggota keluarga yang sudah diundang.',
    punyaLink: 'Kalau Anda punya link undangan, ketuk saja link itu. Link dikirim oleh admin keluarga lewat WhatsApp.',
    judulKode: 'Punya kode dari perangkat lain?',
    labelKode: 'Kode (8 huruf dan angka)',
    bantuanKode: 'Contoh: ABCD-2345. Kode didapat dari menu Saya, lalu Tambah perangkat, di perangkat yang sudah masuk. Kode berlaku 10 menit.',
    tombolKode: 'Masuk dengan kode',
    belumPunya: 'Belum punya link atau kode? Hubungi admin keluarga.',
    bacaPrivasi: 'Baca tentang privasi',
  },

  // Layar membuka link undangan dan kode (layar 2).
  penukaran: {
    undangan: {
      judul: 'Link undangan pribadi',
      isi: 'Ini link pribadi untuk membuka Silsilah Keluarga. Tekan Masuk untuk melanjutkan.',
      catatan: 'Link ini hanya bisa dipakai sekali. Jangan diteruskan ke orang lain.',
    },
    kode: {
      judul: 'Masuk dengan kode',
      isi: 'Kode dari perangkat lain sudah siap. Tekan Masuk untuk melanjutkan.',
      catatan: 'Kode hanya berlaku 10 menit dan hanya bisa dipakai sekali.',
    },
    masuk: 'Masuk',
    sedangMasuk: 'Sedang masuk…',
    cobaLagi: 'Coba lagi',
    keHalamanMasuk: 'Ke halaman masuk',
    linkRusak: 'Link ini tidak lengkap. Pastikan Anda membuka link utuh dari admin.',
    kodeRusak: 'Kode ini tidak lengkap. Pastikan Anda memakai kode utuh dari perangkat yang sudah masuk.',
  },

  browserDalamAplikasi: {
    judul: 'Buka di Chrome atau Safari',
    isi: 'Anda membuka link ini di dalam aplikasi {nama}. Supaya link tidak "tertinggal" di tempat yang salah, buka dulu di Chrome atau Safari.',
    langkah: 'Ketuk tombol di bawah untuk menyalin link, lalu tempel di kolom alamat Chrome atau Safari. Bisa juga lewat menu titik tiga atau tombol bagikan di pojok layar, lalu pilih "Buka di browser".',
    salin: 'Salin link',
    disalin: 'Link sudah disalin. Sekarang buka Chrome atau Safari, lalu tempel di kolom alamat.',
    gagalSalin: 'Link belum bisa disalin. Buka menu titik tiga atau tombol bagikan, lalu pilih "Buka di browser".',
    tetapLanjut: 'Saya tetap ingin lanjut di sini',
  },

  // Layar Selamat datang (layar 3).
  selamatDatang: {
    judul: 'Selamat datang, {nama}!',
    tanya: 'Apakah ini Anda?',
    ya: 'Ya, ini saya',
    bukan: 'Bukan saya',
    yakinJudul: 'Yakin ini bukan Anda?',
    yakinIsi: 'Akses di perangkat ini akan ditutup dan admin langsung diberi tahu, supaya bisa mengirim link yang benar.',
    yakinYa: 'Ya, ini bukan saya',
    yakinBatal: 'Kembali',
    sedangMelapor: 'Sedang memproses…',
    terimaKasihJudul: 'Terima kasih',
    terimaKasihIsi: 'Akses di perangkat ini sudah ditutup dan admin sudah diberi tahu. Mintalah link yang benar kepada admin.',
    tipsJudul: 'Beberapa tips',
    ukuranHuruf: 'Ukuran huruf',
    ukuranIsi: 'Pilih ukuran huruf yang paling nyaman dibaca. Bisa diubah kapan saja di menu Saya.',
    layarUtama: 'Pasang di layar utama',
    layarUtamaIsi: 'Di iPhone: ketuk tombol Bagikan di Safari, lalu pilih "Tambah ke Layar Utama". Di Android: ketuk menu titik tiga di Chrome, lalu pilih "Tambahkan ke layar utama".',
    perangkatBaru: 'Pakai di HP atau laptop lain',
    perangkatBaruIsi: 'Buka menu Saya, lalu pilih Tambah perangkat. Anda akan mendapat kode untuk masuk di perangkat lain, tanpa perlu meminta link baru.',
    lanjut: 'Mulai memakai aplikasi',
  },

  beranda: {
    judul: 'Beranda',
    sapa: 'Halo, {nama}',
    ringkasan: 'Data silsilah sudah termuat: {n} orang di silsilah utama.',
    isi: 'Buka Bagan untuk melihat kartu keluarga dengan garis penghubung, atau Daftar untuk mencari seseorang. Tampilan dan perangkat bisa Anda atur di menu Saya.',
    lihatDaftar: 'Lihat daftar orang',
    lihatBagan: 'Lihat bagan keluarga',
  },

  // Bagan silsilah (langkah 1.22).
  bagan: {
    judul: 'Bagan',
    bingkai: 'Bagan silsilah. Gunakan tombol panah untuk menggeser, tanda + dan − untuk memperbesar dan memperkecil, angka 0 untuk melihat seluruh bagan.',
    perbesar: 'Perbesar',
    perkecil: 'Perkecil',
    pusatkan: 'Pusatkan',
    cari: 'Cari nama',
    petunjukCari: 'Cari nama…',
    cariHasil: '{ke} dari {n}: {nama}',
    cariTidakAda: 'Tidak ada nama yang cocok.',
    sembunyikanMenu: 'Sembunyikan menu bagan',
    tampilkanMenu: 'Tampilkan menu bagan',
    statusLive: 'Tersambung · data terbaru',
    statusDimuat: 'Data dimuat pukul {jam}',
    statusSalinan: 'Data tersimpan di perangkat ini',
    tanpaPangkal: 'Pangkal silsilah belum ditentukan, jadi bagan belum bisa disusun. Hubungi admin.',
    pasanganDari: 'Pasangan {nama}',
    pasanganDariCerai: 'Pasangan {nama} (bercerai)',
    anakDari: 'Anak {nama}',
    anakBerdua: 'Anak {nama} dan {pasangan}',
    pasanganTidakDiketahui: 'Tidak diketahui',
    fokusJudul: 'Menampilkan satu cabang: {nama}',
    tampilkanSemua: 'Tampilkan semua',
    naikKe: 'Naik ke {nama}',
    panel: 'Orang terpilih',
    bukaKeterangan: 'Buka keterangan lengkap',
    fokusCabang: 'Fokus pada cabang ini',
    tutup: 'Tutup',
    lihatDiBagan: 'Lihat di bagan',
    lihatBagan: 'Lihat bagan',
    legenda: {
      judul: 'Keterangan warna',
      sembunyikan: 'Sembunyikan keterangan',
      tampilkan: 'Tampilkan keterangan warna',
      baris: [
        ['tl', 'Laki-laki'],
        ['tp', 'Perempuan'],
        ['x', 'Tidak diketahui'],
        ['pangkal', 'Pangkal'],
        ['wafat', 'Almarhum/Almarhumah'],
      ],
      cerai: 'Bercerai',
      petunjuk: 'Ketuk kartu untuk melihat keterangannya.',
    },
  },


  // Layar Daftar dan Detail orang (langkah 1.21).
  daftar: {
    judul: 'Daftar',
    cari: 'Cari nama',
    petunjukCari: 'Ketik sebagian nama',
    jumlah: '{n} orang',
    tidakAda: 'Tidak ada nama yang cocok.',
    keturunan: 'Keturunan',
    pasangan: 'Pasangan dan lainnya',
    nomor: 'No. {nomor}',
  },
  detail: {
    judul: 'Keterangan orang',
    kembaliKeDaftar: 'Kembali ke Daftar',
    tidakDitemukan: 'Orang ini tidak ditemukan di silsilah.',
    nomor: 'Nomor silsilah',
    panggilan: 'Panggilan',
    lahir: 'Lahir',
    wafat: 'Wafat',
    pekerjaan: 'Pekerjaan',
    catatan: 'Catatan',
    orangTua: 'Orang tua',
    orangTuaLain: 'Orang tua lain',
    duaJalur:
      'Kedua orang tua adalah keturunan pangkal, jadi ada dua jalur ke pangkal. Generasi (GEN) dihitung dari jalur yang paling dekat.',
    jalurTerdekat: 'Jalur terdekat ke pangkal',
    jalurLain: 'Jalur lain',
    jalurSamaDekat: 'Jalur lain (sama dekat)',
    lewatJalurIni: 'Lewat jalur ini: {gen}',
    pernikahan: 'Pernikahan',
    pernikahanKe: 'Pernikahan ke-{n}',
    dengan: 'Dengan',
    keterangan: 'Keterangan',
    generasi: 'Generasi',
    menikah: 'Menikah',
    berakhir: 'Berakhir',
    pasanganTidakDiketahui: 'Pasangan tidak diketahui',
    anak: 'Anak',
    belumAdaAnak: 'Belum ada anak tercatat.',
    anakKe: 'Anak ke-{n}',
  },

  // Keterangan data silsilah (lib/data/): salinan offline dan pembaruan.
  data: {
    offline: 'Anda sedang offline. Yang tampil adalah data tersimpan di perangkat ini dari {waktu}.',
    salinan: 'Server belum bisa dihubungi. Yang tampil adalah data tersimpan di perangkat ini dari {waktu}.',
    salinanTanpaWaktu: 'Server belum bisa dihubungi. Yang tampil adalah data tersimpan di perangkat ini.',
    gagalPerbarui: 'Data belum bisa diperbarui. Yang tampil mungkin bukan data terbaru.',
    hanyaMembaca: 'Untuk sementara data hanya bisa dibaca.',
  },

  // Layar Saya / Pengaturan (layar 20).
  saya: {
    judul: 'Saya',
    tampilan: 'Tampilan',
    ukuranHuruf: 'Ukuran huruf',
    ukuran: { normal: 'Normal', besar: 'Besar', sangatBesar: 'Sangat besar' },
    kontras: 'Kontras tinggi',
    kontrasIsi: 'Warna lebih tegas supaya lebih mudah dibaca.',
    kontrasMenyala: 'Menyala',
    kontrasMati: 'Mati',
    perangkat: 'Perangkat',
    tambahPerangkat: 'Tambah perangkat',
    perangkatSaya: 'Perangkat saya',
    informasi: 'Informasi',
    privasi: 'Privasi',
    admin: 'Untuk pengurus',
    aksesSementara: 'Beri akses sementara',
    duaLangkah: 'Verifikasi dua langkah',
    duaLangkahAktif: 'Verifikasi dua langkah: aktif di perangkat ini.',
    duaLangkahBelum: 'Verifikasi dua langkah: belum di perangkat ini. Layar admin terkunci sampai kode dimasukkan.',
    akun: 'Akun',
    keluar: 'Keluar',
  },

  keluar: {
    judul: 'Keluar',
    isi: 'Pilih cara keluar. Data silsilah yang tersimpan di perangkat ini akan dihapus.',
    iniSaja: 'Keluar dari perangkat ini',
    semua: 'Keluar dari semua perangkat',
    semuaIsi: 'Semua perangkat Anda akan keluar. Untuk masuk lagi, Anda perlu link atau kode baru.',
    batal: 'Batal',
    sedang: 'Sedang keluar…',
    // Pesan di layar Masuk setelah aplikasi mengeluarkan perangkat ini.
    alasan: {
      keluar: 'Anda sudah keluar. Data di perangkat ini sudah dihapus.',
      keluarGagalLain: 'Anda sudah keluar di perangkat ini dan datanya sudah dihapus. Perangkat lain belum bisa dikeluarkan sekarang. Coba lagi nanti dari menu Perangkat saya.',
      dicabut: 'Akses perangkat ini sudah dicabut. Data di perangkat ini sudah dihapus. Hubungi admin kalau Anda merasa ini keliru.',
      berakhir: 'Akses sementara Anda sudah berakhir. Data di perangkat ini sudah dihapus.',
      sesi: 'Sesi Anda berakhir. Data di perangkat ini sudah dihapus. Silakan masuk lagi.',
    },
  },

  // Akses sementara: spanduk hitung mundur di perangkat yang dipinjam, dan
  // layar pengurus untuk memberi akses (layar 22).
  aksesSementara: {
    banner: 'Akses sementara berakhir pukul {jam}. Sisa waktu: {sisa}.',
    segera: 'Segera berakhir. Setelah itu aplikasi keluar sendiri dan data di perangkat ini dihapus.',
    catatan: 'Setelah waktunya habis, aplikasi keluar sendiri dan data di perangkat ini dihapus.',
    judul: 'Beri akses sementara',
    isi: 'Untuk anggota yang ingin memakai laptop atau HP orang lain. Anda akan mendapat kode yang berlaku 10 menit. Setelah kode dipakai, akses berlangsung selama waktu yang dipilih.',
    pilihAnggota: 'Untuk siapa?',
    pilihPlaceholder: 'Pilih nama anggota',
    pilihDurasi: 'Berapa lama?',
    buat: 'Buat kode',
    membuat: 'Membuat kode…',
    kodeJudul: 'Kode untuk {nama}',
    kodeIsi: 'Berikan kode ini kepada {nama}, atau minta ia memindai kode QR. Di perangkat yang dipinjam, pilih "Masuk dengan kode". Kode berlaku {waktu} lagi. Setelah dipakai, akses berlangsung {durasi}.',
    qrLabel: 'Kode QR untuk akses sementara',
    kodeHabis: 'Kode ini sudah tidak berlaku.',
    buatLagi: 'Buat kode lain',
    aktifJudul: 'Akses yang sedang berjalan',
    aktifKosong: 'Tidak ada akses sementara yang sedang berjalan.',
    menunggu: 'Kode belum dipakai, berlaku sampai pukul {jam}',
    berjalan: 'Berakhir pukul {jam}',
    akhiri: 'Akhiri sekarang',
    akhiriJudul: 'Akhiri akses {nama}?',
    akhiriIsi: 'Perangkat itu langsung tidak bisa membuka data lagi.',
    akhiriYa: 'Ya, akhiri',
    batal: 'Batal',
    diakhiri: 'Akses sudah diakhiri.',
    tanpaIzin: 'Anda tidak punya izin memberi akses sementara.',
    perluDuaLangkah: 'Server meminta verifikasi dua langkah lagi. Buka menu Saya, lalu Verifikasi dua langkah, masukkan kodenya, lalu coba lagi.',
  },

  // Kotak masuk (layar 19): pemberitahuan untuk anggota, terutama admin.
  kotakMasuk: {
    judul: 'Kotak masuk',
    kosong: 'Belum ada pemberitahuan.',
    belumDibaca: 'Belum dibaca',
    penting: 'Penting',
    tandai: 'Tandai sudah dibaca',
    cabutPerangkat: 'Cabut perangkat ini',
    cabutPerluDuaLangkah: 'Verifikasi dua langkah dulu untuk mencabut',
    perangkatDicabut: 'Perangkat itu sudah dicabut.',
    jumlahBelumDibaca: '{n} belum dibaca',
    banyak: '99+',
  },

  // Verifikasi dua langkah admin utama (TOTP). "Authenticator" = aplikasi
  // penghasil kode 6 angka (aplikasi Kata Sandi di iPhone, Google
  // Authenticator, dan sejenisnya).
  duaLangkah: {
    judul: 'Verifikasi dua langkah',
    judulGerbang: 'Masukkan kode verifikasi dulu',
    isiGerbang: 'Layar ini khusus admin utama. Untuk membukanya, masukkan kode 6 angka dari aplikasi authenticator. Ini melindungi data keluarga kalau HP atau akun Anda dipakai orang lain.',
    hanyaAdmin: 'Verifikasi dua langkah hanya untuk admin utama.',
    penjelasan: 'Selain masuk dari perangkat terdaftar, admin utama memasukkan kode 6 angka dari aplikasi authenticator. Kodenya berganti setiap 30 detik. Tanpa kode itu, akun admin hanya bisa melakukan apa yang bisa dilakukan anggota biasa.',
    belumAda: 'Belum ada aplikasi authenticator yang terdaftar. Fungsi admin terkunci sampai Anda mendaftarkannya.',
    mulai: 'Daftarkan aplikasi authenticator',
    mulaiCadangan: 'Tambah authenticator cadangan',
    menyiapkan: 'Menyiapkan…',
    langkah1: '1. Buka aplikasi authenticator di HP, misalnya aplikasi Kata Sandi di iPhone (bagian Kode Verifikasi) atau Google Authenticator.',
    langkah2: '2. Pindai kode QR ini dengan aplikasi itu. Kalau tidak bisa memindai, ketik kunci di bawahnya.',
    langkah3: '3. Masukkan kode 6 angka yang muncul di aplikasi itu.',
    qrLabel: 'Kode QR untuk aplikasi authenticator',
    kunciLabel: 'Kunci (kalau tidak bisa memindai)',
    kunciCatatan: 'Kunci ini hanya ditampilkan sekarang. Untuk cadangan, Anda boleh menyalinnya ke kertas yang disimpan di tempat aman, bersama passphrase backup. Jangan kirim lewat chat atau email.',
    kodeLabel: 'Kode 6 angka',
    kodeBantuan: 'Angka yang sedang tampil di aplikasi authenticator.',
    pilihAuthenticator: 'Authenticator yang dipakai',
    verifikasi: 'Verifikasi',
    memeriksa: 'Memeriksa…',
    batal: 'Batal',
    berhasilDaftar: 'Authenticator berhasil didaftarkan. Perangkat ini sudah terverifikasi.',
    berhasilMasuk: 'Kode benar. Perangkat ini sudah terverifikasi.',
    aktif: 'Aktif: perangkat ini sudah terverifikasi dua langkah.',
    terdaftarJudul: 'Authenticator yang terdaftar',
    didaftarkan: 'Didaftarkan {waktu}',
    hapus: 'Hapus',
    hapusJudul: 'Hapus authenticator "{nama}"?',
    hapusIsi: 'Kode dari aplikasi itu tidak berlaku lagi. Pastikan masih ada authenticator lain, atau daftarkan yang baru setelah ini.',
    hapusTerakhir: 'Ini authenticator terakhir. Setelah dihapus, fungsi admin terkunci di perangkat lain sampai Anda mendaftarkan yang baru.',
    hapusYa: 'Ya, hapus',
    dihapus: 'Authenticator sudah dihapus.',
    saranCadangan: 'Saran: daftarkan juga authenticator cadangan, misalnya di HP atau tablet kedua. Kalau HP utama hilang, Anda tetap bisa masuk sebagai admin.',
    hilangJudul: 'Kalau HP atau aplikasi authenticator hilang',
    hilangIsi: 'Pakai authenticator cadangan. Kalau tidak ada sama sekali, pemilik akun Supabase menjalankan prosedur darurat (lihat README): semua authenticator dan perangkat admin dihapus, lalu dibuat satu link masuk baru.',
    namaUtama: 'Utama',
    namaCadangan: 'Cadangan',
    statusGagal: 'Status verifikasi dua langkah belum bisa dibaca.',
  },

  // Layar Tambah perangkat.
  tambahPerangkat: {
    judul: 'Tambah perangkat',
    isi: 'Di perangkat baru, buka aplikasi lalu pindai kode QR ini dengan kamera. Atau pilih "Masuk dengan kode" dan ketik kode di bawah.',
    buat: 'Buat kode',
    membuat: 'Membuat kode…',
    qrLabel: 'Kode QR untuk menambah perangkat',
    kodeLabel: 'Kode',
    berlaku: 'Berlaku {waktu} lagi',
    habis: 'Kode ini sudah tidak berlaku.',
    buatBaru: 'Buat kode baru',
    hanyaSekali: 'Kode hanya bisa dipakai sekali. Jangan berikan kepada orang yang tidak Anda kenal.',
    iphone: 'Pemakai iPhone: layar utama dan Safari tidak berbagi login. Buka ikon di layar utama, pilih "Masuk dengan kode", lalu ketik kode dari sini.',
    sementara: 'Perangkat dengan akses sementara tidak bisa menambah perangkat lain.',
  },

  // Layar Perangkat saya.
  perangkatSaya: {
    judul: 'Perangkat saya',
    isi: 'Perangkat yang sedang masuk dengan nama Anda. Kalau ada yang tidak Anda kenal, atau HP Anda hilang, cabut aksesnya.',
    iniPerangkat: 'Perangkat ini',
    terakhirAktif: 'Terakhir aktif {waktu}',
    masukPada: 'Masuk {waktu}',
    lewat: {
      undangan: 'lewat link undangan',
      kode: 'lewat kode',
      google: 'lewat akun Google',
      sementara: 'akses sementara',
    },
    berakhirPukul: 'Berakhir pukul {jam}',
    cabut: 'Cabut akses',
    cabutJudul: 'Cabut akses perangkat ini?',
    cabutIsiLain: 'Perangkat itu langsung tidak bisa membuka data lagi.',
    cabutIsiIni: 'Ini perangkat yang sedang Anda pakai. Anda akan keluar dan data di sini dihapus.',
    cabutYa: 'Ya, cabut',
    batal: 'Batal',
    kosong: 'Tidak ada perangkat yang sedang masuk.',
    sudahDicabut: 'Akses perangkat sudah dicabut.',
    perkiraan: 'Perkiraan lokasi',
    lokasiTakDiketahui: 'lokasi tidak diketahui',
    tanpaNama: 'Perangkat tanpa nama',
  },

  // Layar Privasi (layar 29): bisa dibuka sebelum dan sesudah masuk.
  privasi: {
    judul: 'Privasi',
    pembuka: 'Halaman ini menjelaskan, dengan bahasa sederhana, data apa yang disimpan aplikasi ini dan berapa lama. Aplikasi ini hanya untuk keluarga dan tidak dibuka untuk umum.',
    bagian: [
      {
        judul: 'Data apa yang disimpan',
        isi: 'Data silsilah yang dicatat keluarga: nama, hubungan keluarga, tanggal dan tempat lahir atau wafat, serta catatan. Semua disimpan di database yang dikunci. Hanya anggota keluarga yang sudah diundang dan masuk dari perangkat yang terdaftar yang bisa membukanya.',
      },
      {
        judul: 'Perangkat yang masuk',
        isi: 'Setiap perangkat yang masuk dicatat: nama perangkat (misalnya "iPhone · Safari"), waktu masuk, dan terakhir aktif. Anda bisa melihat dan mencabut perangkat sendiri di menu Saya.',
      },
      {
        judul: 'Perkiraan lokasi saat masuk',
        isi: 'Saat Anda masuk, admin keluarga menerima pemberitahuan berisi perkiraan kota atau negara, jenis perangkat, dan waktu. Perkiraan ini dibaca dari alamat internet (IP) Anda, jadi sering meleset, terutama di jaringan seluler. Tidak ada GPS, dan aplikasi tidak pernah meminta izin lokasi saat masuk.',
      },
      {
        judul: 'Alamat internet (IP)',
        isi: 'Alamat internet mentah disimpan hanya untuk pemeriksaan keamanan, dan dihapus otomatis setelah 30 hari. Yang disimpan seterusnya hanya perkiraan kota atau negara, jenis perangkat, dan waktu. Alamat internet tidak dikirim ke layanan lain: perkiraan lokasi dihitung dari data yang tersimpan di server aplikasi sendiri.',
      },
      {
        judul: 'Di perangkat Anda',
        isi: 'Aplikasi menyimpan tanda masuk Anda, pilihan tampilan, dan salinan data silsilah terakhir di perangkat, supaya silsilah tetap bisa dibaca saat tidak ada internet. Data kontak (alamat dan nomor HP) tidak pernah disimpan di perangkat. Perangkat dengan akses sementara tidak menyimpan salinan. Saat Anda keluar, saat akses sementara habis, atau saat perangkat dicabut admin, semua data aplikasi di perangkat itu dihapus. Pilihan tampilan (ukuran huruf dan kontras) tetap ada karena bukan data keluarga.',
      },
      {
        judul: 'Akses sementara',
        isi: 'Untuk meminjam laptop atau HP orang lain, Anda bisa meminta akses sementara kepada admin. Setelah waktunya habis, aplikasi keluar sendiri dan data di perangkat itu dihapus.',
      },
    ],
    atribusi: 'Perkiraan lokasi dari alamat IP memakai data DB-IP (db-ip.com), lisensi CC BY 4.0.',
    tautanAtribusi: 'Buka situs DB-IP',
    kembali: 'Kembali',
  },

  // Hasil memakai link undangan atau kode perangkat (Edge Function
  // pakai-undangan dan pakai-kode; lihat src/lib/masuk.js).
  masuk: {
    undangan: {
      tidak_dikenal: 'Link ini tidak dikenali. Pastikan Anda membuka link lengkap dari admin, atau mintalah link baru.',
      sudah_dipakai: 'Link ini sudah dipakai. Kalau Anda belum pernah masuk, hubungi admin keluarga.',
      kedaluwarsa: 'Link ini sudah kedaluwarsa. Mintalah link baru kepada admin.',
      dicabut: 'Link ini sudah dibatalkan. Mintalah link baru kepada admin.',
      terlalu_sering: 'Terlalu banyak percobaan yang salah. Tunggu 15 menit, lalu coba lagi.',
    },
    kode: {
      format_salah: 'Kode terdiri dari 8 huruf dan angka, misalnya ABCD-2345. Periksa lagi kodenya.',
      salah: 'Kode salah. Periksa lagi kodenya, lalu coba lagi.',
      sudah_dipakai: 'Kode ini sudah dipakai. Buat atau mintalah kode baru.',
      kedaluwarsa: 'Kode ini sudah tidak berlaku (lebih dari 10 menit). Buat atau mintalah kode baru.',
      dicabut: 'Kode ini sudah dibatalkan. Buat atau mintalah kode baru.',
      dimatikan: 'Fitur tambah perangkat sedang dimatikan oleh admin.',
      terlalu_sering: 'Terlalu banyak percobaan kode yang salah. Tunggu 15 menit, lalu coba lagi.',
    },
  },

  // Perkiraan lokasi login (Edge Function, data DB-IP Lite). Atribusi wajib
  // ditampilkan di halaman Privasi (lisensi CC BY 4.0).
  lokasi: {
    sekitar: 'sekitar',
    tidakDiketahui: 'lokasi tidak diketahui',
    atribusi: 'Perkiraan lokasi dari alamat IP memakai data DB-IP (db-ip.com), lisensi CC BY 4.0.',
  },

  // Label silsilah: kartu, detail, dan istilah kerabat (src/lib/silsilah/).
  silsilah: {
    almL: 'Alm.',
    almP: 'Almh.',
    almNetral: 'Alm./Almh.',
    pasanganDari: 'Pasangan dari',
    bercerai: 'bercerai',
    dari: 'dari',
    dan: 'dan',
    diriSendiri: 'Diri sendiri',
    lahirDi: 'di',
    sekitar: 'sekitar',
    anakKe: 'Anak ke-',
    jenisPasangan: { istri: 'istri', suami: 'suami', pasangan: 'pasangan' },
    jenisAnak: { kandung: null, sambung: 'Anak sambung', angkat: 'Anak angkat' },
    generasiKe: 'Generasi ke-',
    statusPernikahan: {
      menikah: 'Menikah',
      cerai: 'Bercerai',
      tidak_diketahui: 'Status tidak diketahui',
    },
    bulan: [
      'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni',
      'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember',
    ],
    kerabat: {
      bapak: 'Bapak',
      ibu: 'Ibu',
      orangTua: 'Orang tua',
      mbah: 'Mbah',
      mbahBuyut: 'Mbah buyut',
      mbahCanggah: 'Mbah canggah',
      mbahWareng: 'Mbah wareng',
      kakak: 'Kakak',
      adik: 'Adik',
      kakakAdik: 'Kakak/Adik',
      ipar: 'Ipar',
      keponakan: 'Keponakan',
      sepupu: 'Sepupu',
      anak: 'Anak',
      cucu: 'Cucu',
      cicit: 'Cicit',
      suami: 'Suami',
      istri: 'Istri',
      pasangan: 'Pasangan',
      pakdhe: 'Pakdhe',
      budhe: 'Budhe',
      paklik: 'Paklik',
      bulik: 'Bulik',
      pakdheBudhe: 'Pakdhe/Budhe',
      paklikBulik: 'Paklik/Bulik',
      pakdhePaklik: 'Pakdhe/Paklik',
      budheBulik: 'Budhe/Bulik',
      pamanBibi: 'Paman/Bibi',
    },
  }
}
